disabled_rules: # rule identifiers turned on by default to exclude from running
  - todo
  - nesting

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

identifier_name:
  excluded:
    - id
    - URL
    - GlobalAPIKey
